name: Java CI with Gradle

# Event Trigger
# Master 브랜치에 push, pull request 실행 시 동작
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21

    # gradlew 에 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # build
    - name: Build with Gradle
      run: ./gradlew clean build
